name: Elixir CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      AUTH_USER: admin
      AUTH_PASS: admin
      CI: "true"
    container:
      image: hexpm/elixir:1.11.1-erlang-23.1.1-alpine-3.12.0
    steps:
    - name: "Alpine setup"
      run: |
        apk update
        apk upgrade
        apk add --no-cache make bash zlib openssl openssh git g++ wget curl ca-certificates
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      name: "Cache Mix"
      with:
        path: ~/.mix
        key: ${{ runner.os }}-mix-${{ hashFiles('.tool-versions') }}
    - uses: actions/cache@v1
      name: "Cache Hex"
      with:
        path: ~/.hex
        key: ${{ runner.os }}-hex-${{ hashFiles('.tool-versions') }}
    - uses: actions/cache@v1
      name: "Cache Dependencies"
      with:
        path: deps
        key: ${{ runner.os }}-deps-lock-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
    - name: Install Hex & Rebar
      run: |
        mix local.rebar --force
        mix local.hex --force --if-missing
    - name: Install Dependencies
      run: mix deps.get
    - name: Compile
      run: mix compile --force --warnings-as-errors
    - name: Test
      run: mix test
